### ISSUE TITLE
Tutorial for customizing button background color

### ISSUE THREAD

**Issue by Stoyvo** [fyne-io/developer.fyne.io#12]
### Is your feature request related to a problem? Please describe:
In the tutorials, there should be an example of customizing button colors.

### Is it possible to construct a solution with the existing API?
Yes

### Describe the solution you'd like to see:
A tutorial on setting a button color.

**Comment by Stoyvo** [comment]
Have not written a PR, but here's a working example:

```
package ui

import (
	"image/color"

	"fyne.io/fyne"
	"fyne.io/fyne/widget"
)

type twitchBtn struct {
	widget.Button
}

type twitchBtnRenderer struct {
	fyne.WidgetRenderer
}

func (btn *twitchBtnRenderer) BackgroundColor() color.Color {
	return color.RGBA{R: 145, G: 71, B: 255, A: 255}
}

func (btn *twitchBtn) CreateRenderer() fyne.WidgetRenderer {
	r := btn.Button.CreateRenderer()
	return &twitchBtnRenderer{r}
}

func newTwitchButton() *twitchBtn {
	btn := &twitchBtn{}
	btn.ExtendBaseWidget(btn)
	btn.SetText("TWITCH")
	btn.SetIcon(resourceTwitchlogoPng)

	return btn
}
```

To create the new button, call `newTwitchButton()` when adding your canvas objects.

**Comment by andydotxyz** [comment]
Thanks for this contribution. However I am nervous about publishing a tutorial that uses deprecated APIs.
You might see that BackgroundColor has been deprecated. In 2.0 we plan to remove the concept of widgets having a background. Instead people will be encouraged to position a coloured rectangle underneath, perhaps using a maxlayout in a container for example.

**Comment by Stoyvo** [comment]
@andydotxyz Oh, that's rather unfortunate. Though my comment is likely too late, I feel this is the wrong direction to take. Many languages support elements having a background color property, it brings simplicity to implementation. By requiring manual implementations just for a styling property is a step backwards in being idiomatic. For example lets look at CSS. It succeeded because of it's clear syntax and ease of implementation, if Fyne 2.0 requires manual rectangles positioned underneath a label or button, the use of the library becomes too complex.

Imagine having a button that changes color after using the color picker. How does the button background color reflect the selected choice? Each button would need it's own instance of a rectangle and now the rectangle must be the same size of the tappable area of the button? I hope I'm misunderstanding.

**Comment by andydotxyz** [comment]
Mostly we feel that buttons should change colour only for semantic reason - i.e. the builtin "HighImportance" button configuration. In general the widget API does not offer customisation of colors in the way you describe due to the possibility of UI becoming unreadable or accidentally disadvantaging those with colour blindness.
CSS is a framework for managing style - Fyne does not expose these sorts of APIs at the widget level (only at the canvas level).

I'm not sure that I agree that underlaying a rectangle is more complicated - it is far less code than your example above.
I also would not recommend a standard button that changes colour to the colour a user picked - the text or icon that you include could easily become invisible - perhaps an indicator of picked colour next to the button would be more consistent?

I'll ping @stuartmscott on this as well because he can probably describe the reasons for removing widget backgrounds better than I can.

**Comment by stuartmscott** [comment]
Currently the default assumption is that all widgets have a background of uniform colour, some widgets use `theme.BackgroundColor()`, others use `color.Transparent`, and there are others that use a custom colour which changes based on state.

There are several use cases to cover here; a) widget wants a background colour b) widget doesn't want a background c) a widget wants a background image. Currently b) is rendering a transparent image which is a waste of memory, and computation, and c) has an image rendered over a background colour, which again is a waste of memory, and computation.

The new direction is that widgets don't have a background by default, allowing collection widgets to convey hovered and selected states by changing the color drawn behind the widget. If a widget does want a background colour, or background image, they can use a max layout as @andydotxyz suggested which will resize the rectangle to ensure it always as big as the widget, then your colour button would need to update the rectangle's fill colour and call refresh.

**Comment by Stoyvo** [comment]
@stuartmscott Okay, this makes sense, thank you for taking the time to go into detail about the direction. I do have an ask that a tutorial is dedicated to applying a background color, I truthfully believe this would be a common use case.

Cheers

**Comment by andydotxyz** [comment]
I guess we should consider a place for tutorials of things that are possible but not recommended ;).
A new category of customising is probably needed on the developer site. I will move to adding more content once I have wrapped up the first draft of the Fyne book.

**Comment by stuartmscott** [comment]
+1 for creating a tutorial showing how devs should create backgrounds (either uniform color, image, or more complex). @andydotxyz why would this not be recommended?

**Comment by andydotxyz** [comment]
Mostly I would like that the main tutorials focus on what is best practice or great design ;).
Perhaps we can create a new category of tutorial - perhaps "Customisation" or "Bespoke" or similar?
