### ISSUE TITLE
Hint for deprecated ShowEntryDialog references the wrong type

### ISSUE THREAD

**Issue by pbrown12303** [fyne-io/developer.fyne.io#129]
The entry reads:

> func ShowEntryDialog
> func ShowEntryDialog(title, message string, onConfirm func(string), parent fyne.Window)
> ShowEntryDialog creates a new entry dialog and shows it immediately.
> 
> Deprecated: Use dialog.ShowFormDialog() with a widget.Entry inside instead.
> 

There is no dialog.ShowFormDialog(). The reference should be to dialog.ShowForm()

**Comment by andydotxyz** [comment]
Fixed on develop, the update will roll out on release
