### ISSUE TITLE
In basic windows example goroutine seems to not end

### ISSUE THREAD

**Issue by madwizard** [fyne-io/developer.fyne.io#25]
What: 
Example code: https://developer.fyne.io/tour/basics/windows.html

Environment:
Fedora 33
go version go1.15.8 linux/amd64

Problem:
After closing main window the program seems to still run.

Steps:
1. Paste code into a file (ie. test.go)
2. Run code: go run test.go
3. Wait for second window to show up and dissapear
4. Close main window

Result:
Even after closing the window, the console is not released and the process lingers:

trochej    72955  2.3  0.0 1750860 23404 pts/1   Sl+  20:39   0:00 go run test.go
trochej    73054  4.3  0.2 1960936 67304 pts/1   Sl+  20:39   0:00 /tmp/go-build574735481/b001/exe/test

**Comment by andydotxyz** [comment]
That is correct - the second window is hidden, instead of being closed.
I guess it would be better if the code called Window.Close() instead?

**Comment by andydotxyz** [comment]
I have updated the example accordingly.
