### ISSUE TITLE
how to start the server from these files?

### ISSUE THREAD

**Issue by jeel2331** [fyne-io/developer.fyne.io#28]
i would like to make some changes in the css files but i don't understand how do i start the development server in my computer
please help me to start the server or give me the commands to start the server

my OS: win 10
NOTE: i've already install ruby on machine

**Comment by Jacalz** [comment]
Ah, good point. We should probably have that information added to all our websites. Here is the documentation that can be found for the main site: https://github.com/fyne-io/fyne-io.github.io/blob/master/README.md
