### ISSUE TITLE
please anybody review my pull request

### ISSUE THREAD

**Issue by jeel2331** [fyne-io/developer.fyne.io#31]
it has been 2 day no one reviewed my pull request.

**Comment by Jacalz** [comment]
We will review it when we have time and two days is not what I would call a large amount of time. Excuse me if I sounds rude, but opening issues like this is not really what I would call a professional way of doing things.

**Comment by jeel2331** [comment]
sorry for opening the issue. 
I'm just a beginner so :)

**Comment by Jacalz** [comment]
No worries. We greatly appreciate your contributions. I will make sure that your PR gets the attention that it deserves :)
