### ISSUE TITLE
Add Widget Reference

### ISSUE THREAD

**Issue by aletheia7** [fyne-io/developer.fyne.io#48]
Is there a widget reference for fyne? I want to see a demo of the widgets without downloading/installing fyne.

**Comment by andydotxyz** [comment]
Maybe this helps? https://developer.fyne.io/started/widgets

**Comment by aletheia7** [comment]
Great. Thank you. Here is what I was thinking: [jQuery Mobile Demo](https://demos.jquerymobile.com/1.4.5/).

**Comment by andydotxyz** [comment]
Yes you can install and run the fyne_demo app mentioned in the docs. Or download it for android https://play.google.com/store/apps/details?id=io.fyne.demo
