### ISSUE TITLE
Theme API documentation empty

### ISSUE THREAD

**Issue by iMartyn** [fyne-io/developer.fyne.io#61]
Looks like there's a problem with the documentation generator as https://developer.fyne.io/api/v2.1/theme/ is pretty empty.

![image](https://user-images.githubusercontent.com/962908/145684718-39770d15-172f-41e5-abd1-a2f64732c2cc.png)

**Comment by andydotxyz** [comment]
Sorry, looks like it was somehow corrupted in the 2.1 generation. I updated the script and re-ran. It seems fine now https://developer.fyne.io/api/v2.1/theme/.
