### ISSUE TITLE
Just a advice

### ISSUE THREAD

**Issue by funte** [fyne-io/developer.fyne.io#73]
I'm leaning go and i'm readning fyne toturial, the border layout example at [here](https://developer.fyne.io/container/border) is little not clear, i think you should use button widget replace the original white label text.  
before
![before](https://user-images.githubusercontent.com/9884836/162615525-8971e298-b70f-481f-b87a-8b48cec8a049.png)
after
![after](https://user-images.githubusercontent.com/9884836/162615530-b9ed1e96-ad79-49c9-beb1-ec36f9d8e1f6.png)

**Comment by Jacalz** [comment]
This seems like a good idea. Pull requests are always welcome ;)
It should be easy enough to modify https://github.com/fyne-io/developer.fyne.io/blob/master/container/border.md.
